version: '3.5'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./.postgres:/data/postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=service
    volumes:
      - ./.dockerdata/db:/data/db
    ports:
        - "27017:27017"

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit-dev
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"
